app:
  initUser: "true"
  kafka:
    bookingEventMessageTopic: "booking-event-topic"
    userRegistrationEventMessageTopic: "user-registration-topic"
    kafkaMessageGroupId: "hotel-group"
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/appdatabase?authSource=admin
      auto-index-creation: true
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.xml"
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092

